[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js handles its own routing, so we don't need the redirect to index.html
# which is more appropriate for single-page applications
