name: Deploy to Netlify
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
        
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
        
      - name: Deploy to Netlify (Preview for PRs)
        if: github.event_name == 'pull_request'
        run: |
          netlify deploy \
            --auth "${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --site "${{ secrets.NETLIFY_SITE_ID }}" \
            --dir=out \
            --message "Deploy Preview for PR #${{ github.event.pull_request.number }}" \
            --json
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Deploy to Netlify (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          netlify deploy \
            --auth "${{ secrets.NETLIFY_AUTH_TOKEN }}" \
            --site "${{ secrets.NETLIFY_SITE_ID }}" \
            --dir=out \
            --prod \
            --message "Production deploy from GitHub Actions" \
            --json
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
